# Generated by Django 5.2.7 on 2025-10-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(max_length=200)),
                ('introducao', models.TextField()),
                ('motivo_escolher', models.TextField()),
                ('publico_alvo', models.TextField()),
                ('conteudo_aprendizado', models.TextField()),
                ('profissoes', models.TextField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
