# Generated by Django 5.2.7 on 2025-10-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0002_paginabackend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paginabackend',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='paginabackend',
            name='conteudo_aprendizado',
        ),
        migrations.RemoveField(
            model_name='paginabackend',
            name='introducao',
        ),
        migrations.RemoveField(
            model_name='paginabackend',
            name='motivo_escolher',
        ),
        migrations.RemoveField(
            model_name='paginabackend',
            name='profissoes',
        ),
        migrations.RemoveField(
            model_name='paginabackend',
            name='publico_alvo',
        ),
        migrations.RemoveField(
            model_name='paginabackend',
            name='titulo_principal',
        ),
        migrations.AddField(
            model_name='paginabackend',
            name='conteudo_bibliotecas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paginabackend',
            name='conteudo_fundamentos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paginabackend',
            name='descricao_analiticos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paginabackend',
            name='descricao_iniciantes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paginabackend',
            name='descricao_profissao_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paginabackend',
            name='descricao_profissao_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paginabackend',
            name='profissao_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paginabackend',
            name='profissao_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paginabackend',
            name='titulo_aprendizado',
            field=models.CharField(default='O QUE VOCÊ IRÁ APRENDER?', max_length=200),
        ),
        migrations.AddField(
            model_name='paginabackend',
            name='titulo_indicacao',
            field=models.CharField(default='PARA QUEM ESTA ÁREA É INDICADO?', max_length=200),
        ),
        migrations.AddField(
            model_name='paginabackend',
            name='titulo_profissoes',
            field=models.CharField(default='PROFISSÕES DA ÁREA', max_length=200),
        ),
    ]
