# Generated by Django 5.2.7 on 2025-10-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0003_remove_paginabackend_atualizado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paginabackend',
            name='descricao_analiticos',
        ),
        migrations.RemoveField(
            model_name='paginabackend',
            name='descricao_iniciantes',
        ),
        migrations.RemoveField(
            model_name='paginabackend',
            name='profissao_1',
        ),
        migrations.RemoveField(
            model_name='paginabackend',
            name='profissao_2',
        ),
        migrations.AddField(
            model_name='paginabackend',
            name='salario_profissao_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Salário Backend Developer'),
        ),
        migrations.AddField(
            model_name='paginabackend',
            name='salario_profissao_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Salário API Developer'),
        ),
        migrations.AlterField(
            model_name='paginabackend',
            name='conteudo_bibliotecas',
            field=models.TextField(blank=True, null=True, verbose_name='Bibliotecas e Frameworks'),
        ),
        migrations.AlterField(
            model_name='paginabackend',
            name='conteudo_fundamentos',
            field=models.TextField(blank=True, null=True, verbose_name='A Base de Toda Aplicação'),
        ),
        migrations.AlterField(
            model_name='paginabackend',
            name='descricao_profissao_1',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Backend Developer'),
        ),
        migrations.AlterField(
            model_name='paginabackend',
            name='descricao_profissao_2',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição API Developer'),
        ),
    ]
