# Generated by Django 5.2.7 on 2025-10-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0004_remove_paginabackend_descricao_analiticos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paginabackend',
            name='conteudo_bibliotecas',
        ),
        migrations.RemoveField(
            model_name='paginabackend',
            name='conteudo_fundamentos',
        ),
        migrations.RemoveField(
            model_name='paginabackend',
            name='descricao_profissao_1',
        ),
        migrations.RemoveField(
            model_name='paginabackend',
            name='descricao_profissao_2',
        ),
        migrations.RemoveField(
            model_name='paginabackend',
            name='salario_profissao_1',
        ),
        migrations.RemoveField(
            model_name='paginabackend',
            name='salario_profissao_2',
        ),
        migrations.RemoveField(
            model_name='paginabackend',
            name='titulo_aprendizado',
        ),
        migrations.RemoveField(
            model_name='paginabackend',
            name='titulo_indicacao',
        ),
        migrations.RemoveField(
            model_name='paginabackend',
            name='titulo_profissoes',
        ),
        migrations.AddField(
            model_name='paginabackend',
            name='descricao_principal',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Principal'),
        ),
        migrations.AddField(
            model_name='paginabackend',
            name='faixa_junior',
            field=models.CharField(default='R$ 4.500', max_length=50, verbose_name='Faixa Salarial Júnior'),
        ),
        migrations.AddField(
            model_name='paginabackend',
            name='faixa_pleno',
            field=models.CharField(default='R$ 9.500', max_length=50, verbose_name='Faixa Salarial Pleno'),
        ),
        migrations.AddField(
            model_name='paginabackend',
            name='faixa_senior',
            field=models.CharField(default='R$ 18.000', max_length=50, verbose_name='Faixa Salarial Sênior'),
        ),
        migrations.AddField(
            model_name='paginabackend',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='backend/', verbose_name='Imagem Principal'),
        ),
        migrations.AddField(
            model_name='paginabackend',
            name='motivo_escolher',
            field=models.TextField(blank=True, null=True, verbose_name='Motivos para Escolher Backend'),
        ),
        migrations.AddField(
            model_name='paginabackend',
            name='titulo_principal',
            field=models.CharField(default='Por Que Estudar Backend?', max_length=200, verbose_name='Título Principal'),
        ),
    ]
