# Generated by Django 5.2.7 on 2025-10-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0005_remove_paginabackend_conteudo_bibliotecas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paginabackend',
            name='imagem_principal',
        ),
    ]
