# Generated by Django 5.2.7 on 2025-10-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0006_remove_paginabackend_imagem_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(default='Por Que Estudar Backend?', max_length=200, verbose_name='Título Principal')),
                ('descricao_principal', models.TextField(blank=True, null=True, verbose_name='Descrição Principal')),
                ('motivo_escolher', models.TextField(blank=True, null=True, verbose_name='Motivos para Escolher Backend')),
                ('faixa_junior', models.CharField(default='R$ 4.500', max_length=50, verbose_name='Faixa Salarial Júnior')),
                ('faixa_pleno', models.CharField(default='R$ 9.500', max_length=50, verbose_name='Faixa Salarial Pleno')),
                ('faixa_senior', models.CharField(default='R$ 18.000', max_length=50, verbose_name='Faixa Salarial Sênior')),
            ],
        ),
    ]
