# Generated by Django 5.2.7 on 2025-10-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0009_competencia_habilidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='competencias',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='habilidades',
        ),
    ]
