# Generated by Django 5.2.7 on 2025-11-04 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0010_remove_perfil_competencias_remove_perfil_habilidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Use para definir a ordem na página (ex: 1, 2, 3...)')),
            ],
            options={
                'verbose_name': 'Categoria de Carreira',
                'verbose_name_plural': '1. Categorias de Carreiras',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Carreira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do Card')),
                ('descricao', models.TextField(verbose_name='Descrição Curta')),
                ('url_nome', models.CharField(help_text="Ex: 'pagina_front'. Use '#' se não tiver uma página de detalhe.", max_length=100, verbose_name="Nome da URL (para o botão 'Saiba Mais')")),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Use para definir a ordem dos cards (ex: 1, 2, 3...)')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreiras', to='mapa.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Carreira',
                'verbose_name_plural': '2. Carreiras',
                'ordering': ['categoria__ordem', 'ordem', 'titulo'],
            },
        ),
    ]
