# Generated by Django 5.2.7 on 2025-11-04 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0011_categoria_carreira'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, help_text='Opcional: Imagem de capa do projeto.', null=True, upload_to='fotos_projetos/')),
                ('link_repositorio', models.URLField(blank=True, null=True, verbose_name='Link do Repositório (Ex: GitHub)')),
                ('link_producao', models.URLField(blank=True, null=True, verbose_name='Link da Aplicação (Opcional)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-id'],
            },
        ),
    ]
