# Generated by Django 5.2.7 on 2025-11-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0012_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='imagem',
        ),
    ]
