# Generated by Django 5.2.7 on 2025-11-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0013_remove_projeto_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaCiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(default='Por Que Estudar Ciência de Dados?', max_length=200, verbose_name='Título Principal')),
                ('descricao_principal', models.TextField(blank=True, null=True, verbose_name='Descrição Principal')),
                ('motivo_escolher', models.TextField(blank=True, null=True, verbose_name='Motivos para Escolher Backend')),
                ('faixa_junior', models.CharField(default='R$ 6.000', max_length=50, verbose_name='Faixa Salarial Júnior')),
                ('faixa_pleno', models.CharField(default='R$ 12.000', max_length=50, verbose_name='Faixa Salarial Pleno')),
                ('faixa_senior', models.CharField(default='R$ 25.000', max_length=50, verbose_name='Faixa Salarial Sênior')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='paginamobile',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
