# Generated by Django 5.2.7 on 2025-11-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0014_paginaciencia_paginamobile_atualizado_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaEngenharia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(default='Por Que Estudar Engenharia de Dados?', max_length=200, verbose_name='Título Principal')),
                ('descricao_principal', models.TextField(blank=True, null=True, verbose_name='Descrição Principal')),
                ('motivo_escolher', models.TextField(blank=True, null=True, verbose_name='Motivos para Escolher Engenharia de Dados')),
                ('faixa_junior', models.CharField(default='R$ 7.000', max_length=50, verbose_name='Faixa Salarial Júnior')),
                ('faixa_pleno', models.CharField(default='R$ 14.000', max_length=50, verbose_name='Faixa Salarial Pleno')),
                ('faixa_senior', models.CharField(default='R$ 22.000', max_length=50, verbose_name='Faixa Salarial Sênior')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
