# Generated by Django 5.2.7 on 2025-11-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0015_paginaengenharia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paginafrontend',
            name='conteudo_aprendizado',
        ),
        migrations.RemoveField(
            model_name='paginafrontend',
            name='introducao',
        ),
        migrations.RemoveField(
            model_name='paginafrontend',
            name='profissoes',
        ),
        migrations.RemoveField(
            model_name='paginafrontend',
            name='publico_alvo',
        ),
        migrations.AddField(
            model_name='paginabackend',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paginafrontend',
            name='descricao_principal',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Principal'),
        ),
        migrations.AddField(
            model_name='paginafrontend',
            name='faixa_junior',
            field=models.CharField(default='R$ 4.500', max_length=50, verbose_name='Faixa Salarial Júnior'),
        ),
        migrations.AddField(
            model_name='paginafrontend',
            name='faixa_pleno',
            field=models.CharField(default='R$ 9.500', max_length=50, verbose_name='Faixa Salarial Pleno'),
        ),
        migrations.AddField(
            model_name='paginafrontend',
            name='faixa_senior',
            field=models.CharField(default='R$ 18.000', max_length=50, verbose_name='Faixa Salarial Sênior'),
        ),
        migrations.AlterField(
            model_name='paginabackend',
            name='faixa_pleno',
            field=models.CharField(default='R$ 7.500', max_length=50, verbose_name='Faixa Salarial Pleno'),
        ),
        migrations.AlterField(
            model_name='paginabackend',
            name='faixa_senior',
            field=models.CharField(default='R$ 15.000', max_length=50, verbose_name='Faixa Salarial Sênior'),
        ),
        migrations.AlterField(
            model_name='paginafrontend',
            name='motivo_escolher',
            field=models.TextField(blank=True, null=True, verbose_name='Motivos para Escolher Backend'),
        ),
    ]
