# Generated by Django 5.2.7 on 2025-11-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0017_paginaanalistabi'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaAnaliseSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(default='Por Que Estudar Análise de Segurança?', max_length=200, verbose_name='Título Principal')),
                ('descricao_principal', models.TextField(blank=True, null=True, verbose_name='Descrição Principal')),
                ('motivo_escolher', models.TextField(blank=True, null=True, verbose_name='Motivos para Escolher Análise de Dados')),
                ('faixa_junior', models.CharField(default='R$ 3.000', max_length=50, verbose_name='Faixa Salarial Júnior')),
                ('faixa_pleno', models.CharField(default='R$ 5.500', max_length=50, verbose_name='Faixa Salarial Pleno')),
                ('faixa_senior', models.CharField(default='R$ 16.000', max_length=50, verbose_name='Faixa Salarial Sênior')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='paginaanalistabi',
            name='faixa_pleno',
            field=models.CharField(default='R$ 7.000', max_length=50, verbose_name='Faixa Salarial Pleno'),
        ),
        migrations.AlterField(
            model_name='paginaanalistabi',
            name='titulo_principal',
            field=models.CharField(default='Por Que Estudar Business Intelligence ?', max_length=200, verbose_name='Título Principal'),
        ),
    ]
