# Generated by Django 5.2.7 on 2025-12-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0021_paginaadmredes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaArquitetoNuvem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(default='Por Que Estudar a Área de Arquitetura em Nuvem?', max_length=200, verbose_name='Título Principal')),
                ('descricao_principal', models.TextField(blank=True, null=True, verbose_name='Descrição Principal')),
                ('motivo_escolher', models.TextField(blank=True, null=True, verbose_name='Motivos para Escolher Arquitetura de Nuvem')),
                ('faixa_junior', models.CharField(default='R$ 6.500', max_length=50, verbose_name='Faixa Salarial Júnior')),
                ('faixa_pleno', models.CharField(default='R$ 13.500', max_length=50, verbose_name='Faixa Salarial Pleno')),
                ('faixa_senior', models.CharField(default='R$ 30.000', max_length=50, verbose_name='Faixa Salarial Sênior')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
