# Generated by Django 5.2.7 on 2025-12-21 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0026_paginapesquisador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título da Trilha')),
                ('slug', models.SlugField(help_text='Identificador na URL. Ex: frontend', unique=True)),
                ('descricao', models.TextField(verbose_name='Descrição do Cabeçalho')),
                ('perfil_titulo', models.CharField(default='Perfil Profissional', max_length=200)),
                ('perfil_descricao', models.TextField(verbose_name='Descrição do Perfil')),
                ('tag_1', models.CharField(default='UI', max_length=10)),
                ('tag_2', models.CharField(default='JS', max_length=10)),
                ('tag_3', models.CharField(default='UX', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TrilhaModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Ex: 01', max_length=5, verbose_name='Número')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do Módulo')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição Curta')),
                ('icone', models.CharField(default='fas fa-code', help_text='Classe do FontAwesome. Ex: fas fa-code', max_length=50)),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='mapa.trilha')),
            ],
            options={
                'verbose_name': 'Módulo da Trilha',
                'verbose_name_plural': 'Módulos da Trilha',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='TrilhaTopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(help_text='Ex: Estrutura & Estilo', max_length=100, verbose_name='Agrupador')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Tecnologia')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='mapa.trilhamodulo')),
            ],
        ),
    ]
