# Generated by Django 5.2.7 on 2025-12-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0027_trilha_trilhamodulo_trilhatopico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trilhatopico',
            name='modulo',
        ),
        migrations.AlterModelOptions(
            name='trilha',
            options={'ordering': ['ordem'], 'verbose_name': 'Trilha', 'verbose_name_plural': 'Trilhas'},
        ),
        migrations.RemoveField(
            model_name='trilha',
            name='perfil_descricao',
        ),
        migrations.RemoveField(
            model_name='trilha',
            name='perfil_titulo',
        ),
        migrations.RemoveField(
            model_name='trilha',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='trilha',
            name='tag_1',
        ),
        migrations.RemoveField(
            model_name='trilha',
            name='tag_2',
        ),
        migrations.RemoveField(
            model_name='trilha',
            name='tag_3',
        ),
        migrations.AddField(
            model_name='trilha',
            name='icone',
            field=models.CharField(default='fas fa-road', help_text='Classe do FontAwesome (Ex: fas fa-code)', max_length=50),
        ),
        migrations.AddField(
            model_name='trilha',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Ordem de exibição'),
        ),
        migrations.AddField(
            model_name='trilha',
            name='url_nome',
            field=models.CharField(default='index', help_text="Ex: 'trilha_frontend' ou 'trilha_backend'", max_length=100, verbose_name='Nome da Rota/URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trilha',
            name='descricao',
            field=models.TextField(verbose_name='Descrição Curta'),
        ),
        migrations.DeleteModel(
            name='TrilhaModulo',
        ),
        migrations.DeleteModel(
            name='TrilhaTopico',
        ),
    ]
