# Generated by Django 5.2.7 on 2025-12-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0028_remove_trilhatopico_modulo_alter_trilha_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
